name: Bazel CI
on:
  pull_request:
    branches:
      - main
      - master
      - "**"  # optional: runs on all PRs, regardless of target branch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Bazel
        uses: ngalaiko/bazel-action@2.0.0
        with:
          args: test //...
